language: scala
scala: 2.11.12
jdk: openjdk8
services:
  - docker
script:
  - sbt test
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy_docker.sh $TRAVIS_TAG
env:
  global:
  # DOCKER_USERNAME
  - secure: NfB0rSK4ZpuCtwciT0jUK2vpolIu4JBTjhE2v8pMnILkXttq0dSgPLG40cfotwT0Z/TK1XbwXuOEoiVB8pq7C1TL5l87szBmCASsxIyBJJRUyniCVzDGELd6EKa4Nd92ZS+MFrRypLVMVD4ymCvVgJPj0ODOe8u2nPB7LKq4uRoNVIMaVEQSjUT3FbTHK5p1KThN6zUqSqYAzbRZLcltce1Tr+Edm4zPYAzS/dHzogaRxhXaUVuqw1Csx/P14LVGugYmUOzQDsUl/kprG3wCdT5pSiX40FltQz73CG9WRKfIwLPOiwVgk789w43M/2TzZ4QTXlPGCBMbumwdFGMq4Ob4wV/tGfqvAfX7pAmt3kcgM27uNm3NTP5LWyJEkqOn3vSU+yP9DAh8cbmKlCKbE8uEkxwi7Wx/xfB3sFE7KaFbBW9ldiDfSvux+Y7By3w/TqAAgT2J0iP3DaaubFlcRYs6tMp1jH2P1zEAx/gjkveVOodyjDS5Nvw3Wh0srmgslyayXP/WA4btVlSyuVCCqn20uGXsMJJ7mRqRTXac3lvT+aOHMHyFRdyuorCKC92mNPKfxwv0Vcs7UfZ5bxUlQtQi370Ku7Z35Pm6O06ammfOcVmn4aAC/Xqal3VW+TelnqnxijPHOtWvJI+sWOZOfpbl9bYAWVSApfkd3yGFPVY=
  # DOCKER_PASSWORD
  - secure: dlveE5euNIW3ruBVH/BHoAJ8tdwlSejgbtzWbIMRD389+xtBLQ4rNK5sa6zyyK+67w3U46yEleIHNQeJZGEfy3oZDJaFj3p/7Z52xGDssqTyeDNoiGUewJLxKBJ8B3elkR7V8Zxk/rHhp8q3YL7AqCGh+ktpwea7rUg5uKxIv6KKbimZiBC/AQmPOHNMqVN786evUEu98L4DglXleGgU6Me6cTfHltUhPGgHLjiYjkdgq8SQmHskPnYI5+ewv9/qeISChqp7zTaX97+oiatLLdgHaQOgHPXBMIqUczgbNZ7bBrXMGLbioygeth/shtTq9T8SGWkvroPzq2qTJCULfxXYdruLszCMaP3BLEmye9O/nRmLkWBUUy7RWBZ32mu2B4ifp7YaAc9BDghbHvUglGrEmyGPkZvqpxbI2r3w4MBhj/GXT1Em+X/nf0XTwxUiFVUe3shNVu0vmrvOL4vTWCLFEvjsREOsSNrsmxfuLCn93XQgIDkXZSlbDO+vqxJvQFCGVFdJgECQQOqV7rm+XbKgt+DsZ869Z0XNfhjw8/Zoq4U/feFVs86EHbrpVFbWaYa5flTZE/fzYepISIuoK4CaExIfsGLAZHkeuoV0TOBiOHyg9bA+IvMTkOdLH4JfsiFdLOza79AAHmK4E/mk+m5if6fylgYXCBVT+kRRi70=
